### ISSUE TITLE
The mystery of the missing inbox review

### ISSUE THREAD

**Issue by jjj-unikent** [unikent/programmes-plant#605]
Hi,

I think this might be a one-off but logging it in case needed in future.

We got 2 emails asking us to approve a user (Mike's) revision for French and Comp Lit MA.

However, when I went to the plant inbox, there were no requests there for me to approve!

*puts on trenchcoat and fedora.

I did a test 'send to ems' myself for another programme, and that request showed up OK in the inbox.

I checked the French and Comp Lit entry, and Mike's revision had not already been published by someone else (my old version is still the live version).
 
The time on his (unpublished) revision is 17:07 (not sure if plant is still 1 hr behind) and it still shows the 'this version has not been sent to EMS' message'. The time on the email request is 18:10.

I wondered if Mike might have deleted his revision after he sent the request, but when I log in as a user I can’t see a way of deleting revisions.

Angela wondered if it might have been something to do with the rollout.  It's French and Comp Lit again so it might have been caused when the issue with the apply link was fixed?

I've emailed Mike to ask if he did anything unusual after submitting the request but he hasn't replied yet.

Anyway, as I mentioned, the test 'send to ems' I did worked OK so it's up to you whether you want to investigate this or close and wait to see if it happens again.

Thanks,

JJ

**Comment by eg270-unikent** [comment]
@aw285-unikent do you know if this issue is still happening?

**Comment by aw285-unikent** [comment]
@eg270-unikent I'm not aware of this happening so I will close and reopen if it happens again.
