### ISSUE TITLE
New text added to field not highlighed in 'review' view

### ISSUE THREAD

**Issue by jjj-unikent** [unikent/programmes-plant#610]
Hi, this is just a suggestion for an enhancement in the future.  Currently if someone adds text to a previously blank field (then sends for approval), the change is not highlighted in the 'review' view.  Thanks, JJ

**Comment by eg270-unikent** [comment]
@aw285-unikent is this still an issue? Have you any examples for us to look at?

**Comment by aw285-unikent** [comment]
@eg270-unikent I think this is still an issue. See the' staff research interests into' field on this one: 

https://webtools-test.kent.ac.uk/programmes/2015/pg/programmes/585/review/7906 

A similar issue is that when people add text to the bottom of an existing field that already has text in it, that isn't highlighted very well either. Only the last word before the new text is highlighted in green - I don't find that a major issue though as I use the diff tool more as a guide to let me know what fields to check over and I think Fritha does the same. If it's got any highlights/lines in it, I check it all.

**Comment by eg270-unikent** [comment]
OK have added to sprint backlog for us to investigate.

**Comment by eg270-unikent** [comment]
I've returned this to dev on trello

**Comment by eg270-unikent** [comment]
This should now be fixed.
