### ISSUE TITLE
Global settings field (or Immutable field) permissions storage

### ISSUE THREAD

**Issue by jna-unikent** [unikent/programmes-plant#657]
Permissions for global settings are currently being stored with a `ug_field...` prefix in the `usersys_permissions` table in the database. It would make more sense for the permissions to be stored as something like `global_field...` since global settings are neither UG nor PG.

This is however not a straightforward change since one would need to write a script to migrate all the previous global setting permissions to the new form.

**Comment by eg270-unikent** [comment]
@jna-unikent can we discuss the value of doing this? Possibly do a non-breaking change for new values?

**Comment by eg270-unikent** [comment]
@jna-unikent was this discussed last week?
