### ISSUE TITLE
'Email all users' button on users table/list within programmes plant

### ISSUE THREAD

**Issue by aw285-unikent** [unikent/programmes-plant#698]
As EMS

I would like an 'email all users' button on the 'users' table page within the programmes plant that would allow me to email all programmes plant users (can exclude hyperadmins to save them getting irrelevant emails). 

So that we can email all programmes plant users to message them. 

We have tried to maintain a email list for programmes plant users outside of the programmes plant but this has been ineffective. 

We currently cut and paste the 'users table' into excel, remove the redundant columns from it, remove hyperadmins, copy the email addresses into Word, add semi colons between each of them and then copy them into outlook. Is it possible to automate this at all please? 

If it's not possible have it so what when you click the 'email all users' button, it opens outlook with all the users' email addresses populating in the 'to' field, it is possible for it to generate a plain text file of all the users' email addresses with a semi colon between them, so we can copy and paste this into the 'to' field in outlook please? 

Thanks

Angela 

@eg270-unikent @lrhm-unikent

**Comment by eg270-unikent** [comment]
Hi @aw285-unikent is this something you would still like us to implement?

**Comment by aw285-unikent** [comment]
@eg270-unikent Hi Edele, yes this would be really useful. Currently I do an elaborate cut and paste job to email users.

**Comment by eg270-unikent** [comment]
Hi @aw285-unikent this will be quite difficult to implement due to the email sympa API not being very nice. Instead, we could setup a mailing list with all of the programmes plant users. However, this would need to be kept up to date as users add/leave the Programmes Plant

**Comment by aw285-unikent** [comment]
Hi @eg270-unikent Ok no worries. We did have a mailing list but people forgot to keep it up to date so it wasn't very reliable. Happy for you to close this and just continue with the existing method.
Thanks
Angela

**Comment by eg270-unikent** [comment]
Ok will close this.
