### ISSUE TITLE
Ability for hyperadmins to signal to each other? Short note field in programme admin section

### ISSUE THREAD

**Issue by aw285-unikent** [unikent/programmes-plant#715]
Hello, 

If you review a programme that has been edited by a user via the hyperadmin inbox and 'request changes from a user' (using the blue button and message function at the bottom of the 'Review changes screen'), this status is not reflected in the inbox against that programme. 

Please could a small 'changes requested' flag be added against the programme in the inbox, which would be removed if the user sends another change for that programme to EMS? 

Otherwise hyperadmins may get confused and think it's a new change that's been sent in, when instead it's one that is being worked on. 

Thanks
Angela

**Comment by eg270-unikent** [comment]
Hi @aw285-unikent is this met by the 'Request changes from author' button or is there still outstanding work to be done on this?

**Comment by aw285-unikent** [comment]
HI @eg270-unikent I think it would be good to have a way for us hyperadmins to signal to each other if we are working on a certain programme in the inbox. Perhaps a field in the programme admin section where we can leave a very short note saying 'being dealt with by Fritha' etc and this note could output under the programme title in the editing inbox? Does that make sense? This would be in addition to the longer note field that I have requested to be added where we can leave more substantial notes about the status of the programme etc. 
Thanks

Angela

**Comment by aw285-unikent** [comment]
@eg270-unikent this would be really useful when we get our new staff member and also when other colleagues help us edit/publish the programmes during busier times.

**Comment by eg270-unikent** [comment]
OK I've changed the title to reflect the change and added to sprint backlog

**Comment by gjmh-unikent** [comment]
@aw285-unikent just to clarify these two note fields should only be available to hyperadmins?
Also where would you prefer them placed within the form page, top/bottom?

**Comment by aw285-unikent** [comment]
@gjmh-unikent sorry I was sick today, just trying to catch up a bit now. Yes both only accessible to hyperadmins.

Please could they go on the programmes page editing form, at the bottom of the 'Page administration' section (or even better right at the very bottom under the 'programme deliveries' section but I don't mind if that's too fiddly).

**Comment by eg270-unikent** [comment]
@aw285-unikent both 'Notes' and 'Short note' appears at the bottom of the programmes page editing page. Can this issue be closed?

**Comment by aw285-unikent** [comment]
?yes thanks


Angela

________________________________
