### ISSUE TITLE
access the PP api from api.kent

### ISSUE THREAD

**Issue by jna-unikent** [unikent/programmes-plant#716]
Just wondering if it'll be a good idea to proxy the programmes plant from api.kent so that going to api.kent.ac.uk/api/v1/programmes/[blah] will serve up data from webtools.kent.ac.uk/programmes/api/[blah]. So that all our data is all in one place...

It could be as simple as putting in a ticket to OPS.

**Comment by eg270-unikent** [comment]
Keeping this ticket as it's still something we would like to do in the future.

**Comment by eg270-unikent** [comment]
This was done some time ago, closing. https://api.kent.ac.uk/api/programmes/{endpoints}
