### ISSUE TITLE
POS and MCR codes editable and not read only in hyperadmin view (UG)

### ISSUE THREAD

**Issue by aw285-unikent** [unikent/programmes-plant#757]
Hi @eg270-unikent @mb324-unikent 

I noticed the POS and MCR codes for UG programmes are editable and not read-only on UG programme pages. Whereas they are read only on PG. 

We have had a few reports today that the POS / MCR codes in the SITS spreadsheet are wrong. I just wanted to know: if the SITS team update a UG POS or MCR code, will this change automatically show on the programme page (the one within the programmes plant)?  I assume this happens for PG? 

Thanks

Angela

**Comment by eg270-unikent** [comment]
This was rolled out in December 2014.
