### ISSUE TITLE
Error when adding/saving a user who doesn't have a department in LDAP

### ISSUE THREAD

**Issue by jna-unikent** [unikent/programmes-plant#762]
![bug](https://cloud.githubusercontent.com/assets/4138097/4629997/cc0a4330-53a9-11e4-884d-698b06deefe3.png)

**Comment by eg270-unikent** [comment]
Should be fixed on test - https://github.com/unikent/programmes-plant/commit/5ac912b3684011aed7c3937a6f3011205ac01725

**Comment by eg270-unikent** [comment]
Rolled out. Closing.
