### ISSUE TITLE
Link box error in IE

### ISSUE THREAD

**Issue by frithassell** [unikent/programmes-plant#771]
Hello, a PP user has reported an issue with the Link tool when using IE. It looks like all three options from the 'Link type' drop-down are merging. When you click OK nothing happens and the whole screen freezes. Screenshot attached. Thanks Fritha.
![pp link box in ie](https://cloud.githubusercontent.com/assets/3090031/5185762/9ecd0d36-74b9-11e4-994e-b338aa7fc67c.jpg)

**Comment by eg270-unikent** [comment]
Update ckeditor
