### ISSUE TITLE
Intermittent error All tabs showing all content

### ISSUE THREAD

**Issue by frithassell** [unikent/programmes-plant#799]
Hi, I first noticed yesterday but By the time I'd written the issue it had gone away. It's happening again this morning though. On Ancient History with a term in Rome all content is showing on all tabs from Course content onwards. I haven't noticed on any other programmes yet but will update you if I get any more examples. On Firefox.

![tab-contents-18 12 14](https://cloud.githubusercontent.com/assets/3090031/5486571/f3ee4350-869f-11e4-8053-eac22891bead.jpg)

**Comment by eg270-unikent** [comment]
This was a bug in our code where the section was not ending correctly after course structure where module session was set to 'none' so all other tab content appeared under 'course structure' tab.
I've fixed this in our code and it is due to be rolled out tomorrow 3rd Feb
