### ISSUE TITLE
Ancient History with a Term in Rome modules

### ISSUE THREAD

**Issue by frithassell** [unikent/programmes-plant#801]
@aw285-unikent 
Hi, the modules are not outputting for this programme where:

POS in Programmes Plant and SDS match
Location code is correct
No content in Modules Intro override
Taught programme ticked
'None' has been removed from Module Session in PP and programme re-published

I can't think of anything else that could be stopping the modules from outputting on the course page, please can you take a look?

MCR code is PAHI000105MA-FD

Thanks
Fritha

**Comment by eg270-unikent** [comment]
Hi @frithassell this was an issue with the PG modules not being populated correctly. This was fixed on Friday 30th January and modules are now showing for this programme. I'm closing this issue as a result.
