### ISSUE TITLE
SITSImport - if IPOs exist but don't match mode of study, apply page breaks

### ISSUE THREAD

**Issue by eg270-unikent** [unikent/programmes-plant#815]
Taken from FP#608554.
http://www.kent.ac.uk/courses/postgraduate/apply-online/214

This course has a delivery for full-time and part-time but mode of study is full-time only. Our logic for the apply page messes up as a result of this and no course options are shown.

@Angela - should we trust the mode_of_study from the Programmes Plant or should we take the SITS data as the source of truth and do our logic on that?

The <inUse> flag has been removed from the SITS XML data feed. I've queried whether this is correct. Without this flag we are assuming that anything SITS sends us should be processed.

**Comment by aw285-unikent** [comment]
@eg270-unikent I will check the correct delivery wiith Eleri in English and let you know. Ordinarily I would say to trust the course pages because the schools are the editors but then I don't know where SITS gets it info from.
