### ISSUE TITLE
Centre for Finance course snippet pulling differnet content to the course pages.

### ISSUE THREAD

**Issue by frithassell** [unikent/programmes-plant#816]
The Kent Centre for Finance is using the programmes snippet but is not pulling in the same content that is showing on the main programmes page. See http://www.kent.ac.uk/finance-centre/programmes/Postgraduate/finance-managment-msc.html
The correct content is showing here http://www.kent.ac.uk/courses/postgraduate/742/finance-and-management .

I've tried to trace this through the versions function in the Programmes PLant and it seems to be a very old or even the first version (one difference being an extra fact on the National Rankings list, but I can't find a version which exactly matches): http://www.kent.ac.uk/courses/postgraduate/preview/5992f2710e37ecc90c941a919a5a8eb744634d96#!overview

It's not clear at  the moment if this is a one off or if there are more examples. Nicola in KBS is checking through all programmes.

Thanks
Fritha

**Comment by eg270-unikent** [comment]
This was due to user error where they were pointing at the wrong year in the snippet. 
@frithassell looks like they've removed the snippet completely from their page instead of just updating the year to be 'current'
