### ISSUE TITLE
Snippetise/Centralise code for the fees data tables

### ISSUE THREAD

**Issue by eg270-unikent** [unikent/programmes-plant#824]
To prevent inconsistencies between the EMS and Finance data tables can we centralise the code so that when we update one data table it updates the other one?

**Comment by eg270-unikent** [comment]
This has been done in pantheon - see https://github.com/unikent/pantheon/pull/1044 and https://github.com/unikent/pantheon/pull/1045

**Comment by eg270-unikent** [comment]
Rolled out but needs implementing - @cs462-unikent can you pick this up on our next BAU days?

**Comment by thybag** [comment]
Yep, should hopefully just be a matter of swapping out the existing datatables code for the snippet :)

**Comment by eg270-unikent** [comment]
As per our meeting earlier today (30th April), we have decided that EMS will point directly to Finance's data fees table. This negates the need for the snippet so I'm closing this issue.
