### ISSUE TITLE
Release Plan - UG 2016 launch

### ISSUE THREAD

**Issue by cs462-unikent** [unikent/programmes-plant#826]
11AM Switch over.

- [x] Check we have booking slot for rollout
- [x] Ensure 2017 IPO are all set up
- [x] Update back end year value
- [x] Update front end year value for UG
- [x] Ensure caches flush correctly
- [x] Check fee data is still coming through  - fee year is set to 2015 - (Plus correct disclaimer text is showing)
- [x] Double check previous year banner shows correctly.
- [x] Remove manual 2016 cron (as "current" cron will now do this)
- [x] Add cron to keep running 2015 data
- [x] Update "configinator" entries to display correct year - check 2016 versions. (new one for 2015)
- [x] Ensure image/js/css paths are updated for 2015 index. e.g. http://www-test.kent.ac.uk/courses/undergraduate/2015/
- [x] Uncheck new programme checkbox's 
- [x]  Ask websols to warn publishers that if they have hardcoded years in to the xcri snippets they will need to manually update this.

**Comment by eg270-unikent** [comment]
Guy has checked the XML and the 2017 IPOs are now there, I've checked this out with a published programme:

2015 entry: https://evision.kent.ac.uk/urd/sits.urd/run/siw_ipp_lgn.login?process=siw_ipp_app&code1=UBIA000105BS-PD&code2=0002
2016 entry: https://evision.kent.ac.uk/urd/sits.urd/run/siw_ipp_lgn.login?process=siw_ipp_app&code1=UBIA000105BS-PD&code2=0004

**Comment by eg270-unikent** [comment]
@aw285-unikent the new programme checkboxes should not be unchecked - we had to do this manually as we don't believe we did this for previous launches.
