### ISSUE TITLE
Export of POS codes

### ISSUE THREAD

**Issue by eg270-unikent** [unikent/programmes-plant#838]
Raised by Angela in an email.

The following link was sent to Angela: https://webtools.kent.ac.uk/programmes/export/current/postgraduate/taught/pos-codes

Can we compare this against our XCRI feed and ensure all programmes we output for XCRI are included in the above export?

*I think the spreadsheet might be missing programmes that we'd want to output in the XCRI feed and therefore need Alan to supply JACS3 codes for. These are programmes that don't take direct applications via SITS so won't have programme delivery data (eg our Law specialisms).*

*Unfortunately due to the size of our course portfolio, I don’t know what all these programmes are so can't add them to the spreadsheet. Is there any way you could send me a list of programmes that are in the programme plant but are not on the spreadsheet you've already sent me, please?*

**Comment by gjmh-unikent** [comment]
@aw285-unikent can you confirm if it is just postgraduate taught programmes you want, or all programmes not in that sheet regardless of level/type?

**Comment by aw285-unikent** [comment]
hi @gjmh-unikent Yes just post graduate taught programmes please.

**Comment by eg270-unikent** [comment]
@aw285-unikent can this be closed as Greg emailed you the csv file last Tues (2nd June)?
