### ISSUE TITLE
Ability to bulk upload JACS3 codes to the programmes plant

### ISSUE THREAD

**Issue by eg270-unikent** [unikent/programmes-plant#851]
As EMS,

I want to have the ability to bulk upload JACS3 codes to the programmes plant

so that these do not need to be entered manually

**Comment by eg270-unikent** [comment]
@aw285-unikent this one is a bit difficult without knowing what format the file will be in. Will there just be one big file? If so, will there be an identifier so we can map the codes to the correct programmes?

Or is there going to be a file for each programme (potentially with multiple JACS codes inside?)

**Comment by aw285-unikent** [comment]
@eg270-unikent Hello, I have asked colleagues for a sample of the spreadsheet to send you (or the final one if available).

**Comment by eg270-unikent** [comment]
This was done here: https://github.com/unikent/programmes-plant/pull/856 closing
